<?php
$tablemeta = array (
  'id' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 13,
    'num' => 0,
  ),
  'id_individu' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id_individu',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 1,
  ),
  'identifiant' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'identifiant',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 3,
    'flags' => 6,
    'num' => 2,
  ),
  'mot_de_passe' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'mot_de_passe',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 4,
    'num' => 3,
  ),
  'id_langue_application' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id_langue_application',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 4,
  ),
  'courriel' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'courriel',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 5,
  ),
  'id_profil' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id_profil',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 4,
    'num' => 6,
  ),
  'role' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'role',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 4,
    'num' => 7,
  ),
  'etat' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'etat',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 30,
    'flags' => 4,
    'num' => 8,
  ),
  'theme' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'theme',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 4,
    'num' => 9,
  ),
  'manytoone_autocomplete_minchars' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'manytoone_autocomplete_minchars',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 2,
    'flags' => 4,
    'num' => 10,
  ),
  'acces_restreint_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'acces_restreint_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 11,
  ),
  'url_acces_restreint' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'url_acces_restreint',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 12,
  ),
  'table_des_matieres_wiki_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'table_des_matieres_wiki_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 13,
  ),
  'log_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'log_o_n',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 1,
    'flags' => 4,
    'num' => 14,
  ),
  'debug_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'debug_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 15,
  ),
  'tt_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'tt_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 16,
  ),
  'sticky_tt_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'sticky_tt_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 17,
  ),
  'tt_couleur_bg' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'tt_couleur_bg',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 4,
    'num' => 18,
  ),
  'stats_page_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'stats_page_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 19,
  ),
  'trace_db_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'trace_db_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 20,
  ),
  'contexte_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'contexte_o_n',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 21,
  ),
  'biodiversite_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'biodiversite_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 22,
  ),
  'golf_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'golf_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 23,
  ),
  'uploads_organismes_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'uploads_organismes_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 24,
  ),
  'uploads_utilisateurs_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'uploads_utilisateurs_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 25,
  ),
  'icones_detaillees_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'icones_detaillees_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 26,
  ),
  'icones_estampillage_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'icones_estampillage_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 27,
  ),
  'afficher_portrait_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'afficher_portrait_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 28,
  ),
  'copie_courriel_o_n' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'copie_courriel_o_n',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 4,
    'num' => 29,
  ),
  'courriel_copie' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'courriel_copie',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 30,
  ),
  'date_dernier_login' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'date_dernier_login',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 31,
  ),
  'nombre_de_logins' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'nombre_de_logins',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 0,
    'num' => 32,
  ),
  'texte_contrat_utilisateur' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'texte_contrat_utilisateur',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => -1,
    'flags' => 0,
    'num' => 33,
  ),
  'date_signature_contrat' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'date_signature_contrat',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 34,
  ),
  'datagrid' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'datagrid',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => -1,
    'flags' => 0,
    'num' => 35,
  ),
  'datagrid_csv' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'datagrid_csv',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => -1,
    'flags' => 0,
    'num' => 36,
  ),
  'google_docs_courriel' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'google_docs_courriel',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 37,
  ),
  'google_docs_code' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'google_docs_code',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 38,
  ),
  'google_album_checkpoint' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'google_album_checkpoint',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 8,
    'flags' => 0,
    'num' => 39,
  ),
  'commentaire' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'commentaire',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => 65535,
    'flags' => 0,
    'num' => 40,
  ),
  'id_creation' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id_creation',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 41,
  ),
  'date_creation' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'date_creation',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 4,
    'num' => 42,
  ),
  'id_modification' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'id_modification',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 43,
  ),
  'date_modification' => 
  array (
    'table' => 'app_utilisateur',
    'table_type' => 'InnoDB',
    'name' => 'date_modification',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 4,
    'num' => 44,
  ),
)
?>