<?php
$tablemeta = array (
  'id' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 13,
    'num' => 0,
  ),
  'id_titre' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id_titre',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 1,
  ),
  'prenom' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'prenom',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 2,
  ),
  'sexe' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'sexe',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 1,
    'flags' => 0,
    'num' => 3,
  ),
  'nom' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'nom',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 200,
    'flags' => 4,
    'num' => 4,
  ),
  'numero_ss' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'numero_ss',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 5,
  ),
  'compte_bancaire' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'compte_bancaire',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 6,
  ),
  'id_document_signature' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id_document_signature',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 0,
    'num' => 7,
  ),
  'id_document_portrait' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id_document_portrait',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 8,
  ),
  'commentaire_portrait' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'commentaire_portrait',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => 65535,
    'flags' => 0,
    'num' => 9,
  ),
  'courriel' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'courriel',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 200,
    'flags' => 0,
    'num' => 10,
  ),
  'calendrier' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 255,
    'flags' => 0,
    'num' => 11,
  ),
  'site_internet' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'site_internet',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 255,
    'flags' => 0,
    'num' => 12,
  ),
  'telephone_fixe' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'telephone_fixe',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 13,
  ),
  'telephone_mobile' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'telephone_mobile',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 14,
  ),
  'contact_alternatif' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'contact_alternatif',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 255,
    'flags' => 0,
    'num' => 15,
  ),
  'date_naissance' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'date_naissance',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 16,
  ),
  'annee_naissance' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'annee_naissance',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '4,0',
    'flags' => 0,
    'num' => 17,
  ),
  'lieu_naissance' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'lieu_naissance',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 18,
  ),
  'nationalite' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'nationalite',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 19,
  ),
  'passeport_nom_prenom' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'passeport_nom_prenom',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 250,
    'flags' => 0,
    'num' => 20,
  ),
  'passeport_numero' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'passeport_numero',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 21,
  ),
  'passeport_date_expiration' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'passeport_date_expiration',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 22,
  ),
  'profession' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'profession',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 250,
    'flags' => 0,
    'num' => 23,
  ),
  'date_deces' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'date_deces',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 24,
  ),
  'tour_de_cou' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'tour_de_cou',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 25,
  ),
  'tour_de_poitrine' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'tour_de_poitrine',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 26,
  ),
  'tour_de_taille' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'tour_de_taille',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 27,
  ),
  'tour_de_bassin' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'tour_de_bassin',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 28,
  ),
  'pointure' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'pointure',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 29,
  ),
  'taille' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'taille',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,0',
    'flags' => 0,
    'num' => 30,
  ),
  'poids' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'poids',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,2',
    'flags' => 0,
    'num' => 31,
  ),
  'etp_poids_kg' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'etp_poids_kg',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,2',
    'flags' => 0,
    'num' => 32,
  ),
  'etp_pulses_per_minute' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'etp_pulses_per_minute',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '3,0',
    'flags' => 0,
    'num' => 33,
  ),
  'etp_systole_mm_hg' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'etp_systole_mm_hg',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '3,0',
    'flags' => 0,
    'num' => 34,
  ),
  'date_mesure' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'date_mesure',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 35,
  ),
  'entree_college' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'entree_college',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 30,
    'flags' => 0,
    'num' => 36,
  ),
  'sortie_college' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'sortie_college',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 30,
    'flags' => 0,
    'num' => 37,
  ),
  'golf_licence' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'golf_licence',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 255,
    'flags' => 0,
    'num' => 38,
  ),
  'golf_index' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'golf_index',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '5,2',
    'flags' => 0,
    'num' => 39,
  ),
  'golf_url_federation' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'golf_url_federation',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 255,
    'flags' => 0,
    'num' => 40,
  ),
  'pas_de_courriel_o_n' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'pas_de_courriel_o_n',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 1,
    'flags' => 4,
    'num' => 41,
  ),
  'signature_courriel' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'signature_courriel',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => 65535,
    'flags' => 0,
    'num' => 42,
  ),
  'identifiant_google' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'identifiant_google',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 43,
  ),
  'code_google' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'code_google',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 44,
  ),
  'tz_offset_google' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'tz_offset_google',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 6,
    'flags' => 0,
    'num' => 45,
  ),
  'calendrier_rencontres_nom' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_rencontres_nom',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 46,
  ),
  'calendrier_rencontres_url' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_rencontres_url',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 47,
  ),
  'calendrier_rencontres_uri' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_rencontres_uri',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 48,
  ),
  'calendrier_rencontres_refresh' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_rencontres_refresh',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 49,
  ),
  'calendrier_contacts_nom' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_contacts_nom',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 50,
  ),
  'calendrier_contacts_url' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_contacts_url',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 51,
  ),
  'calendrier_contacts_uri' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_contacts_uri',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 400,
    'flags' => 0,
    'num' => 52,
  ),
  'calendrier_contacts_refresh' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'calendrier_contacts_refresh',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 53,
  ),
  'google_calendar_entries' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'google_calendar_entries',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '4,0',
    'flags' => 0,
    'num' => 54,
  ),
  'commentaire' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'commentaire',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => 65535,
    'flags' => 0,
    'num' => 55,
  ),
  'id_creation' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id_creation',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 56,
  ),
  'date_creation' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'date_creation',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 4,
    'num' => 57,
  ),
  'id_modification' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'id_modification',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 11,
    'flags' => 4,
    'num' => 58,
  ),
  'date_modification' => 
  array (
    'table' => 'individu',
    'table_type' => 'InnoDB',
    'name' => 'date_modification',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 4,
    'num' => 59,
  ),
)
?>