<?php

$this->m_securityMap["enveloppes"] = "view";
$this->m_securityMap["datagrid_view"] = "view";
$this->m_securityMap["datagrid_google_export"] = "view";
$this->m_securityMap["datagrid_google_texte_export"] = "view";
$this->m_securityMap["assocope_to_google_export"] = "view";
$this->m_securityMap["enveloppes_sans_courriel_uniquement"] = "view";
$this->m_securityMap["envoi_groupe"] = "view";
$this->m_securityMap["geolocalisations"] = "view";
$this->m_securityMap["courriels"] = "view";
$this->m_securityMap["export_google"] = "view";
$this->m_securityMap["noms"] = "view";
$this->m_securityMap["coordonnees"] = "view";
$this->m_securityMap["vcards"] = "view";
$this->m_securityMap["exportations"] = "view";
$this->m_securityMap["sans_courriel"] = "view";
$this->m_securityMap["avec_courriel"] = "view";
$this->m_securityMap["sans_adresse_postale"] = "view";
$this->m_securityMap["sans_courriel_et_sans_adresse_postale"] = "view";
$this->m_securityMap["copier_individus_dans_presse_papier"] = "view";
$this->m_securityMap["node_table_search"] = "view";
$this->m_securityMap["full_base_search"] = "view";
$this->m_securityMap["labels_search"] = "view";
$this->m_securityMap["createMarkerLonLat"] = "view";
$this->m_securityMap["html_popup"] = "view";
$this->m_securityMap["licence_golf"] = "view";
$this->m_securityMap["competences"] = "view";
$this->m_securityMap["synchro_google_contacts"] = "view";
$this->m_securityMap["itineraires"] = "view";
$this->m_securityMap["listedit"] = "view";


?>
